#!/bin/sh
#
# Install-time build script for xkit.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/xkit.make6.a7.

bin/mythryld <<EOF
    make7::freeze "src/lib/x-kit/xkit.make6";
EOF

if   [ -f "src/lib/x-kit/xkit.make6.a7" ]
then
     echo "                     src/lib/x-kit/build:   Successfully created src/lib/x-kit/xkit.make6.a7:"
     echo "                     src/lib/x-kit/build:   `ls -l src/lib/x-kit/xkit.make6.a7`"
else
     echo "Error:               src/lib/x-kit/build:   Failed to create src/lib/x-kit/xkit.make6.a7"
     exit 1
fi

exit 0;
