#!/bin/sh
#
# Install-time build script for memory.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/c-glue-lib/memory/memory.make6.a7.

bin/mythryld <<EOF
    make7::freeze "src/lib/c-glue-lib/memory/memory.make6";
EOF

if   [ -f "src/lib/c-glue-lib/memory/memory.make6.a7" ]
then
     echo "         src/lib/c-glue-lib/memory/build:   Successfully created src/lib/c-glue-lib/memory/memory.make6.a7:"
     echo "         src/lib/c-glue-lib/memory/build:   `ls -l src/lib/c-glue-lib/memory/memory.make6.a7`"
else
     echo "         src/lib/c-glue-lib/memory/build:   Failed to create src/lib/c-glue-lib/memory/memory.make6.a7"
     exit 1
fi

exit 0;
