#!/bin/sh
#
# Install-time build script for basicwin.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/tut/basicwin/basicwin.make6.frozen.

bin/mythryld <<EOF
    make7::freeze "src/lib/x-kit/tut/basicwin/basicwin.make6";
EOF

if   [ -f "src/lib/x-kit/tut/basicwin/basicwin.make6.frozen" ]
then
     echo "     .../example/basicwin/build-basicwin:   Successfully created: src/lib/x-kit/tut/basicwin/basicwin.make6.frozen"
     echo "     .../example/basicwin/build-basicwin:   `ls -l src/lib/x-kit/tut/basicwin/basicwin.make6.frozen`"
else
     echo "     .../example/basicwin/build-basicwin:   Failed to create src/lib/x-kit/tut/basicwin/basicwin.make6.frozen"
     exit 1
fi

exit 0;
