#!/bin/sh
#
# Install-time build script for calc.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/tut/calc/calc.make6.frozen.

bin/mythryld <<EOF
    make7::freeze "src/lib/x-kit/tut/calc/calc.make6";
EOF

if   [ -f "src/lib/x-kit/tut/calc/calc.make6.frozen" ]
then
     echo "   src/lib/x-kit/tut/calc/build-calc:   Successfully created: src/lib/x-kit/tut/calc/calc.make6.frozen"
     echo "   src/lib/x-kit/tut/calc/build-calc:   `ls -l src/lib/x-kit/tut/calc/calc.make6.frozen`"
else
     echo "   src/lib/x-kit/tut/calc/build-calc:   Failed to create src/lib/x-kit/tut/calc/calc.make6.frozen"
     exit 1
fi

exit 0;
