#!/bin/sh
#
# Install-time build script for add.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/tut/add/add.make6.a7.

bin/mythryld <<EOF
    make7::freeze "src/lib/x-kit/tut/add/add.make6";
EOF

if   [ -f "src/lib/x-kit/tut/add/add.make6.a7" ]
then
     echo "     src/lib/x-kit/tut/add/build-add:   Successfully created: src/lib/x-kit/tut/add/add.make6.a7"
     echo "     src/lib/x-kit/tut/add/build-add:   `ls -l src/lib/x-kit/tut/add/add.make6.a7`"
else
     echo "     src/lib/x-kit/tut/add/build-add:   Failed to create src/lib/x-kit/tut/add/add.make6.a7"
     exit 1
fi

exit 0;
