#!/bin/sh
#
# Install-time build script for lib7.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/thread-kit/threadkit-lib/cm-descr/lib7.make6.a7.

bin/mythryld <<EOF
    make7::freeze "src/lib/thread-kit/threadkit-lib/cm-descr/lib7.make6";
EOF

if   [ -f "src/lib/thread-kit/threadkit-lib/cm-descr/lib7.make6.a7" ]
then
     echo "   .../threadkit-lib/cm-descr/build-lib7:   Successfully created src/lib/thread-kit/threadkit-lib/cm-descr/trace-threadkit.make6.a7:"
     echo "   .../threadkit-lib/cm-descr/build-lib7:   `ls -l src/lib/thread-kit/threadkit-lib/cm-descr/trace-threadkit.make6.a7`"
else
     echo "   .../threadkit-lib/cm-descr/build-lib7:   Failed to create src/lib/thread-kit/threadkit-lib/cm-descr/trace-threadkit.make6.a7"
     exit 1
fi

exit 0;
