#!/bin/sh
#
# Install-time build script for sml-ast.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/compiler/lower/tools/sml-ast.make6.a7.

bin/mythryld <<EOF
    make7::freeze "src/lib/compiler/lower/tools/sml-ast.make6";
EOF

if   [ -f "src/lib/compiler/lower/tools/sml-ast.make6.a7" ]
then
     echo "           .../lower/tools/build-sml-ast:   Successfully created src/lib/compiler/lower/tools/sml-ast.make6.a7:"
     echo "           .../lower/tools/build-sml-ast:   `ls -l src/lib/compiler/lower/tools/sml-ast.make6.a7`"
else
     echo "           .../lower/tools/build-sml-ast:   Failed to create src/lib/compiler/lower/tools/sml-ast.make6.a7"
     exit 1
fi

exit 0;
