#!/bin/sh
#
# Install-time build script for widgets.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/tut/widget/widgets.make6.a7.

bin/mythryld <<EOF
    make7::freeze "src/lib/x-kit/tut/widget/widgets.make6";
EOF

if   [ -f "src/lib/x-kit/tut/widget/widgets.make6.a7" ]
then
     echo "  lib/x-kit/tut/widget/build-widgets:   Successfully created: src/lib/x-kit/tut/widget/widgets.make6.a7"
     echo "  lib/x-kit/tut/widget/build-widgets:   `ls -l src/lib/x-kit/tut/widget/widgets.make6.a7`"
else
     echo "  lib/x-kit/tut/widget/build-widgets:   Failed to create src/lib/x-kit/tut/widget/widgets.make6.a7"
     exit 1
fi

exit 0;
