#!/bin/sh
#
# Install-time build script for core-threadkit.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/thread-kit/src/core-threadkit.make6.a7.

bin/mythryld <<EOF
    make7::freeze "src/lib/thread-kit/src/core-threadkit.make6";
EOF

if   [ -f "src/lib/thread-kit/src/core-threadkit.make6.a7" ]
then
     echo " .../thread-kit/src/build-core-threadkit:   Successfully created src/lib/thread-kit/src/core-threadkit.make6.a7:"
     echo " .../thread-kit/src/build-core-threadkit:   `ls -l src/lib/thread-kit/src/core-threadkit.make6.a7`"
else
     echo " .../thread-kit/src/build-core-threadkit:   Failed to create src/lib/thread-kit/src/core-threadkit.make6.a7"
     exit 1
fi

exit 0;
