#!/bin/sh
#
# Install-time build script for pixmap-editor.make6.
#
# We will normally be run as a result of a toplevel "make rest".
#
# Our main result is the freezefile src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.a7.

bin/mythryld <<EOF
    make7::freeze "src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6";
EOF

if   [ -f "src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.a7" ]
then
     echo "       bitmap-editor/build-bitmap-editor:   Successfully created: src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.a7"
     echo "       bitmap-editor/build-bitmap-editor:   `ls -l src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.a7`"
else
     echo "       bitmap-editor/build-bitmap-editor:   Failed to create src/lib/x-kit/tut/bitmap-editor/bitmap-editor.make6.a7"
     exit 1
fi

exit 0;
